# Generated by Django 4.2.16 on 2026-01-03 21:06

import os
from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_superuser(apps, schema_editor):
    CustomUser = apps.get_model('student_management_app', 'CustomUser')
    
    # Check if superuser already exists
    if CustomUser.objects.filter(is_superuser=True).exists():
        return
    
    # Get credentials from environment or use defaults
    email = os.environ.get('SUPERUSER_EMAIL', 'admin@gmail.com')
    password = os.environ.get('SUPERUSER_PASSWORD', 'admin')
    first_name = os.environ.get('SUPERUSER_FIRST_NAME', 'Admin')
    last_name = os.environ.get('SUPERUSER_LAST_NAME', 'User')
    
    CustomUser.objects.create(
        email=email,
        password=make_password(password),
        first_name=first_name,
        last_name=last_name,
        user_type=1,  # Admin user type
        is_staff=True,
        is_superuser=True,
        is_active=True
    )

def reverse_superuser(apps, schema_editor):
    CustomUser = apps.get_model('student_management_app', 'CustomUser')
    CustomUser.objects.filter(email='admin@gmail.com', is_superuser=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_alter_customuser_id'),
    ]

    operations = [
        migrations.RunPython(create_superuser, reverse_superuser),
    ]